[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[tool.poetry]
name = "snagem"
version = "0.1.0"
description = ""
license = "MIT"
readme = "README.md"
repository = "https://github.com/jcmdln/snagem"
authors = ["Johnathan C. Maudlin <jcmdln@gmail.com>"]
packages = [{ include = "snagctl" }, { include = "snagd" }]

[tool.poetry.dependencies]
python = "^3.6"
alembic = "^1.4.3"
boto3 = "^1.16.1"
celery = { version = "^5.0.1", extras = ["sqlalchemy"] }
click = "^7.1.2"
fastapi = { version = "^0.61", extras = ["all"] }
humanfriendly = "^8.2"
youtube_dl = "^2020.9.20"

[tool.poetry.dev-dependencies]
bandit = "^1.6.2"
black = "20.8b1"
coverage = "^5.3"
flake8 = "^3.8.4"
mypy = "^0.790"
poetry = "^1.1.3"
pydocstyle = "^5.1.1"
pyls-black = "^0.4.6"
pytest = "^6.1.1"
sphinx = "^3.2.1"
tox = "^3.20.1"

[tool.poetry.dev-dependencies.python-language-server]
extras = [
    "flake8",
    "mccabe",
    "pycodestyle",
    "pydocstyle",
    "pyflakes",
    "pylint",
    "rope",
]
version = "^0.35.1"

[tool.poetry.scripts]
snagctl = "snagctl.main:main"
snagd = "snagd.main:main"

#
# Extras
#

[tool.black]
line-length = 79

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py3{6,7,8,9}
ignore_basepython_conflict = true
isolated_build = true
minversion = 3.20.0
skip_missing_interpreters = true

[testenv]
basepython = python3
whitelist_externals = poetry

setenv =
    PYTHONDONTWRITEBYTECODE=true
    PYTHONUNBUFFERED=true

commands =
    {[testenv:dependency]commands}
    {[testenv:lint]commands}

#
# Bundles
#

[testenv:docs]
commands =
    {[testenv:sphinx]commands}

[testenv:lint]
commands =
    {[testenv:bandit]commands}
    {[testenv:black]commands}
    {[testenv:flake8]commands}
    {[testenv:mypy]commands}

[testenv:unit]
commands =
    {[testenv:coverage]commands}
    {[testenv:pytest]commands}

#
# Tests
#

[testenv:bandit]
whitelist_externals = poetry
commands =
    poetry run bandit --quiet -r snagctl/ snagd/

[testenv:black]
whitelist_externals = poetry
commands =
    poetry run black --diff --quiet snagctl/ snagd/

[testenv:coverage]
whitelist_externals = poetry
commands =
    poetry run coverage --version

[testenv:dependency]
whitelist_externals = poetry
commands =
    poetry install
    poetry run snagctl --help
    poetry run snagd --help

[testenv:flake8]
whitelist_externals = poetry
commands =
    poetry run flake8 --show-source --quiet snagctl/ snagd/

[testenv:mypy]
whitelist_externals = poetry
commands =
    poetry run mypy --no-error-summary --pretty snagctl/
    poetry run mypy --no-error-summary --pretty snagd/

[testenv:pytest]
whitelist_externals = poetry
commands =
    poetry run pytest --version

[testenv:sphinx]
whitelist_externals = poetry
commands =
    poetry run sphinx --version
"""
