[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "snagem"
version = "0.1.0"
description = ""
license = "MIT"
readme = "README.md"
repository = "https://github.com/jcmdln/snagem"
authors = ["Johnathan C. Maudlin <jcmdln@gmail.com>"]
packages = [{ include = "snagemctl" }, { include = "snagemd" }]

[tool.poetry.dependencies]
python = "^3.6"
alembic = "^1.4"
boto3 = "^1.15"
celery = { version = "^5.0", extras = ["sqlalchemy"] }
click = "^7.1"
fastapi = { version = "^0.61", extras = ["all"] }
humanfriendly = "^8.2"
youtube_dl = "^2020.9"

[tool.poetry.dev-dependencies]
bandit = "^1.6"
black = "20.8b1"
coverage = "^5.3"
flake8 = "^3.8"
mypy = "^0.790"
pydocstyle = "^5.1"
pylint = "^2.6"
pyls-black = "^0.4"
pytest = "^6.1"
sphinx = "^3.2"

[tool.poetry.dev-dependencies.python-language-server]
extras = [
    "flake8",
    "mccabe",
    "pycodestyle",
    "pydocstyle",
    "pyflakes",
    "pylint",
    "rope",
]
version = "^0.35"

[tool.poetry.scripts]
snagemctl = "snagemctl.snagemctl:main"
snagemd = "snagemd.snagemd:main"

#
# Extras
#

[tool.black]
line-length = 79

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py3{6,7,8,9}
ignore_basepython_conflict = true
isolated_build = true

[testenv]
basepython = python3
whitelist_externals = poetry

setenv =
    PYTHONDONTWRITEBYTECODE=true
    PYTHONUNBUFFERED=true

commands =
    {[testenv:dependency]commands}
    {[testenv:lint]commands}

#
# Bundles
#

[testenv:lint]
commands =
    {[testenv:bandit]commands}
    {[testenv:black]commands}
    {[testenv:flake8]commands}
    {[testenv:mypy]commands}

[testenv:unit]
commands =
    {[testenv:coverage]commands}
    {[testenv:pytest]commands}

#
# Tests
#

[testenv:bandit]
whitelist_externals = poetry
commands =
    poetry run bandit --verbose snagemctl/ snagemd/

[testenv:black]
whitelist_externals = poetry
commands =
    poetry run black --verbose snagemctl/ snagemd/

[testenv:coverage]
whitelist_externals = poetry
commands =
    poetry run coverage --verbose snagemctl/ snagemd/

[testenv:dependency]
whitelist_externals = poetry
commands =
    poetry install --verbose
    poetry run snagemctl
    poetry run snagemd

[testenv:flake8]
whitelist_externals = poetry
commands =
    poetry run flake8 --verbose snagemctl/ snagemd/

[testenv:mypy]
whitelist_externals = poetry
commands =
    poetry run mypy --verbose snagemctl/ snagemd/

[testenv:pytest]
whitelist_externals = poetry
commands =
    poetry --version

[testenv:sphinx]
whitelist_externals = poetry
commands =
    poetry --version
"""
